[package]
name = "u16_tic_tac_toe"
version = "0.1.0"
authors = ["Eike Schulze <eike.schulze@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
